name: Upload Video

on:
  workflow_dispatch:
    inputs:
      link:
        description: Link to the video to upload
        required: true

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup yt-dlp
        uses: AnimMouse/setup-yt-dlp@v1
        with:
          with-ffmpeg: true

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Run uploader
        run: bun start "${{ github.event.inputs.link }}"
        env:
          githubToken: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          uploadToYouTube: ${{ vars.UPLOAD_TO_YOUTUBE }}
          uploadToTelegram: ${{ vars.UPLOAD_TO_TELEGRAM }}
          telegramApiId: ${{ secrets.TELEGRAM_API_ID }}
          telegramApiHash: ${{ secrets.TELEGRAM_API_HASH }}
          telegramSession: ${{ secrets.TELEGRAM_SESSION }}
          telegramChannel: ${{ secrets.TELEGRAM_CHANNEL }}
          youtubeCredentials: ${{ secrets.YOUTUBE_CREDENTIALS }}
